'use client';
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "./store/store";
import ModeProvider from "./components/ModeProvider";

// const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <ModeProvider>
        {children}
      </ModeProvider>
    </Provider>
  );
}
